"""initial schema with unified matches

Revision ID: 0b992ae7763c
Revises: 
Create Date: 2026-01-26 08:08:10.218052+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic
revision: str = '0b992ae7763c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.

    This function is called when running 'alembic upgrade'.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('feature_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('atp_id', sa.String(length=20), nullable=True),
    sa.Column('wta_id', sa.String(length=20), nullable=True),
    sa.Column('itf_id', sa.String(length=20), nullable=True),
    sa.Column('nationality_ioc', sa.String(length=3), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('turned_pro_year', sa.Integer(), nullable=True),
    sa.Column('hand', sa.String(length=15), nullable=True),
    sa.Column('backhand', sa.String(length=20), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atp_id'),
    sa.UniqueConstraint('itf_id'),
    sa.UniqueConstraint('wta_id')
    )
    op.create_table('scrape_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('task_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('priority >= 1 AND priority <= 10', name='ck_priority_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scrape_queue_status', 'scrape_queue', ['status', 'priority', 'created_at'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tour', sa.String(length=15), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_ioc', sa.String(length=3), nullable=True),
    sa.Column('surface', sa.String(length=20), nullable=True),
    sa.Column('indoor_outdoor', sa.String(length=10), nullable=True),
    sa.Column('atp_link', sa.String(length=255), nullable=True),
    sa.Column('wta_link', sa.String(length=255), nullable=True),
    sa.Column('itf_link', sa.String(length=255), nullable=True),
    sa.Column('betting_link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_code', 'tour', name='uq_tournament_code_tour')
    )
    op.create_table('update_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_type', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_update_log_type_date', 'update_log', ['update_type', 'created_at'], unique=False)
    op.create_table('player_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', 'source', name='uq_player_alias_source')
    )
    op.create_index('idx_player_aliases_alias', 'player_aliases', ['alias'], unique=False)
    op.create_table('player_review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraped_name', sa.String(length=255), nullable=False),
    sa.Column('scraped_source', sa.String(length=50), nullable=False),
    sa.Column('scraped_external_id', sa.String(length=50), nullable=True),
    sa.Column('match_external_id', sa.String(length=100), nullable=True),
    sa.Column('tournament_name', sa.String(length=255), nullable=True),
    sa.Column('suggested_player_1_id', sa.Integer(), nullable=True),
    sa.Column('suggested_player_1_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('suggested_player_2_id', sa.Integer(), nullable=True),
    sa.Column('suggested_player_2_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('suggested_player_3_id', sa.Integer(), nullable=True),
    sa.Column('suggested_player_3_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_player_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['suggested_player_1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['suggested_player_2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['suggested_player_3_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_queue_status', 'player_review_queue', ['status', 'created_at'], unique=False)
    op.create_table('tournament_editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('surface', sa.String(length=20), nullable=True),
    sa.Column('draw_size', sa.Integer(), nullable=True),
    sa.Column('prize_money_usd', sa.Integer(), nullable=True),
    sa.Column('atp_edition_id', sa.String(length=50), nullable=True),
    sa.Column('wta_edition_id', sa.String(length=50), nullable=True),
    sa.Column('itf_edition_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'year', name='uq_tournament_year')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('tournament_edition_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.String(length=20), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=True),
    sa.Column('player_a_id', sa.Integer(), nullable=False),
    sa.Column('player_b_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_datetime', sa.DateTime(), nullable=True),
    sa.Column('court', sa.String(length=100), nullable=True),
    sa.Column('odds_a', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('odds_b', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('odds_source', sa.String(length=50), nullable=True),
    sa.Column('odds_updated_at', sa.DateTime(), nullable=True),
    sa.Column('prediction_a', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('prediction_model_version', sa.String(length=50), nullable=True),
    sa.Column('prediction_updated_at', sa.DateTime(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.String(length=100), nullable=True),
    sa.Column('score_structured', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=True),
    sa.Column('match_datetime', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('retirement_set', sa.Integer(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_a_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_edition_id'], ['tournament_editions.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_matches_match_date', 'matches', ['match_date'], unique=False)
    op.create_index('idx_matches_player_a', 'matches', ['player_a_id'], unique=False)
    op.create_index('idx_matches_player_b', 'matches', ['player_b_id'], unique=False)
    op.create_index('idx_matches_scheduled_date', 'matches', ['scheduled_date'], unique=False)
    op.create_index('idx_matches_status', 'matches', ['status'], unique=False)
    op.create_index('idx_matches_tournament', 'matches', ['tournament_edition_id'], unique=False)
    op.create_table('elo_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('rating_before', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('rating_after', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('surface', sa.String(length=20), nullable=True),
    sa.Column('is_career_peak', sa.Boolean(), nullable=False),
    sa.Column('rating_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_elo_ratings_match', 'elo_ratings', ['match_id'], unique=False)
    op.create_index('idx_elo_ratings_player_date', 'elo_ratings', ['player_id', 'rating_date'], unique=False)
    op.create_table('match_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('feature_set_id', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'feature_set_id', name='uq_match_features')
    )
    op.create_index('idx_match_features_match', 'match_features', ['match_id'], unique=False)
    op.create_index('idx_match_features_set', 'match_features', ['feature_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.

    This function is called when running 'alembic downgrade'.
    Note: Some migrations may not be fully reversible.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_match_features_set', table_name='match_features')
    op.drop_index('idx_match_features_match', table_name='match_features')
    op.drop_table('match_features')
    op.drop_index('idx_elo_ratings_player_date', table_name='elo_ratings')
    op.drop_index('idx_elo_ratings_match', table_name='elo_ratings')
    op.drop_table('elo_ratings')
    op.drop_index('idx_matches_tournament', table_name='matches')
    op.drop_index('idx_matches_status', table_name='matches')
    op.drop_index('idx_matches_scheduled_date', table_name='matches')
    op.drop_index('idx_matches_player_b', table_name='matches')
    op.drop_index('idx_matches_player_a', table_name='matches')
    op.drop_index('idx_matches_match_date', table_name='matches')
    op.drop_table('matches')
    op.drop_table('tournament_editions')
    op.drop_index('idx_review_queue_status', table_name='player_review_queue')
    op.drop_table('player_review_queue')
    op.drop_index('idx_player_aliases_alias', table_name='player_aliases')
    op.drop_table('player_aliases')
    op.drop_index('idx_update_log_type_date', table_name='update_log')
    op.drop_table('update_log')
    op.drop_table('tournaments')
    op.drop_index('idx_scrape_queue_status', table_name='scrape_queue')
    op.drop_table('scrape_queue')
    op.drop_table('players')
    op.drop_table('feature_sets')
    # ### end Alembic commands ###
