"""Add match_date_estimated column

Revision ID: db3fab1b850a
Revises: 541094708d60
Create Date: 2026-02-01 09:14:31.904470+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic
revision: str = 'db3fab1b850a'
down_revision: Union[str, None] = '541094708d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.

    This function is called when running 'alembic upgrade'.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_date_estimated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.

    This function is called when running 'alembic downgrade'.
    Note: Some migrations may not be fully reversible.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'match_date_estimated')
    # ### end Alembic commands ###
