"""add_temporal_order_to_matches

Revision ID: 541094708d60
Revises: 0b992ae7763c
Create Date: 2026-01-27 09:16:34.971678+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic
revision: str = '541094708d60'
down_revision: Union[str, None] = '0b992ae7763c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.

    This function is called when running 'alembic upgrade'.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('temporal_order', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_matches_temporal_order'), 'matches', ['temporal_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.

    This function is called when running 'alembic downgrade'.
    Note: Some migrations may not be fully reversible.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_temporal_order'), table_name='matches')
    op.drop_column('matches', 'temporal_order')
    # ### end Alembic commands ###
