"""Add player seed fields to matches

Revision ID: 319bd5f03dbf
Revises: a1b2c3d4e5f6
Create Date: 2026-02-03 06:55:05.025465+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic
revision: str = '319bd5f03dbf'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.

    This function is called when running 'alembic upgrade'.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('player_a_seed', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('player_b_seed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.

    This function is called when running 'alembic downgrade'.
    Note: Some migrations may not be fully reversible.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'player_b_seed')
    op.drop_column('matches', 'player_a_seed')
    # ### end Alembic commands ###
