"""
One-time backfill: populate Tournament.timezone from city/country.

Uses a static mapping approach (no external API calls) with:
1. City-level overrides for multi-timezone countries (US, Australia, Canada, Russia, Brazil)
2. Country-level fallback for single-timezone countries

Usage:
    python scripts/backfill_tournament_timezones.py [--dry-run]
"""
import argparse
import logging

from sqlalchemy import select

from teelo.db.models import Tournament
from teelo.db.session import get_session
from teelo.utils.geo import city_to_country

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

# Single-timezone country mapping (covers >90% of tennis venues)
COUNTRY_TO_TIMEZONE: dict[str, str] = {
    "Albania": "Europe/Tirane",
    "Andorra": "Europe/Andorra",
    "Argentina": "America/Argentina/Buenos_Aires",
    "Austria": "Europe/Vienna",
    "Azerbaijan": "Europe/Baku",
    "Bahrain": "Asia/Bahrain",
    "Belgium": "Europe/Brussels",
    "Bolivia": "America/La_Paz",
    "Bosnia": "Europe/Sarajevo",
    "Bosnia and Herzegovina": "Europe/Sarajevo",
    "Bulgaria": "Europe/Sofia",
    "Chile": "America/Santiago",
    "China": "Asia/Shanghai",
    "Chinese Taipei": "Asia/Taipei",
    "Colombia": "America/Bogota",
    "Congo": "Africa/Brazzaville",
    "Costa Rica": "America/Costa_Rica",
    "Croatia": "Europe/Zagreb",
    "Czech Republic": "Europe/Prague",
    "Czechia": "Europe/Prague",
    "Denmark": "Europe/Copenhagen",
    "Dominican Republic": "America/Santo_Domingo",
    "Ecuador": "America/Guayaquil",
    "Egypt": "Africa/Cairo",
    "Estonia": "Europe/Tallinn",
    "Finland": "Europe/Helsinki",
    "France": "Europe/Paris",
    "Georgia": "Asia/Tbilisi",
    "Germany": "Europe/Berlin",
    "Great Britain": "Europe/London",
    "Greece": "Europe/Athens",
    "Hong Kong": "Asia/Hong_Kong",
    "Hungary": "Europe/Budapest",
    "India": "Asia/Kolkata",
    "Ireland": "Europe/Dublin",
    "Israel": "Asia/Jerusalem",
    "Italy": "Europe/Rome",
    "Ivory Coast": "Africa/Abidjan",
    "Japan": "Asia/Tokyo",
    "Latvia": "Europe/Riga",
    "Luxembourg": "Europe/Luxembourg",
    "Malaysia": "Asia/Kuala_Lumpur",
    "Moldova": "Europe/Chisinau",
    "Monaco": "Europe/Monaco",
    "Morocco": "Africa/Casablanca",
    "Netherlands": "Europe/Amsterdam",
    "New Zealand": "Pacific/Auckland",
    "North Macedonia": "Europe/Skopje",
    "Norway": "Europe/Oslo",
    "Pakistan": "Asia/Karachi",
    "Paraguay": "America/Asuncion",
    "Peru": "America/Lima",
    "Philippines": "Asia/Manila",
    "Poland": "Europe/Warsaw",
    "Portugal": "Europe/Lisbon",
    "Qatar": "Asia/Qatar",
    "Romania": "Europe/Bucharest",
    "Rwanda": "Africa/Kigali",
    "San Marino": "Europe/San_Marino",
    "Saudi Arabia": "Asia/Riyadh",
    "Serbia": "Europe/Belgrade",
    "Singapore": "Asia/Singapore",
    "Slovakia": "Europe/Bratislava",
    "Slovenia": "Europe/Ljubljana",
    "South Korea": "Asia/Seoul",
    "Spain": "Europe/Madrid",
    "Sweden": "Europe/Stockholm",
    "Switzerland": "Europe/Zurich",
    "Taiwan": "Asia/Taipei",
    "Thailand": "Asia/Bangkok",
    "Tunisia": "Africa/Tunis",
    "Turkey": "Europe/Istanbul",
    "UAE": "Asia/Dubai",
    "United Arab Emirates": "Asia/Dubai",
    "United Kingdom": "Europe/London",
    "Uruguay": "America/Montevideo",
    "USA": "America/New_York",
    "Uzbekistan": "Asia/Tashkent",
    "Vietnam": "Asia/Ho_Chi_Minh",
}

# City-level overrides for multi-timezone countries
CITY_TIMEZONE_OVERRIDES: dict[str, str] = {
    # United States
    "new york": "America/New_York",
    "miami": "America/New_York",
    "charleston": "America/New_York",
    "delray beach": "America/New_York",
    "cleveland": "America/New_York",
    "lexington": "America/New_York",
    "columbus": "America/New_York",
    "atlanta": "America/New_York",
    "newport": "America/New_York",
    "winston salem": "America/New_York",
    "winston-salem": "America/New_York",
    "ponte vedra beach": "America/New_York",
    "bloomfield hills": "America/New_York",
    "knoxville": "America/New_York",
    "savannah": "America/New_York",
    "charlottesville": "America/New_York",
    "little rock": "America/New_York",
    "albany": "America/New_York",
    "sumter": "America/New_York",
    "cary": "America/New_York",
    "concord": "America/New_York",
    "tallahassee": "America/New_York",
    "sarasota": "America/New_York",
    "baton rouge": "America/Chicago",
    "new haven": "America/New_York",
    "washington": "America/New_York",
    "washington dc": "America/New_York",
    "indianapolis": "America/Indiana/Indianapolis",
    "cincinnati": "America/New_York",
    "chicago": "America/Chicago",
    "dallas": "America/Chicago",
    "houston": "America/Chicago",
    "austin": "America/Chicago",
    "tyler": "America/Chicago",
    "tulsa": "America/Chicago",
    "waco": "America/Chicago",
    "midland": "America/Chicago",
    "memphis": "America/Chicago",
    "sioux falls": "America/Chicago",
    "champaign": "America/Chicago",
    "lincoln": "America/Chicago",
    "indian wells": "America/Los_Angeles",
    "san diego": "America/Los_Angeles",
    "san jose": "America/Los_Angeles",
    "san francisco": "America/Los_Angeles",
    "los angeles": "America/Los_Angeles",
    "stanford": "America/Los_Angeles",
    "newport beach": "America/Los_Angeles",
    "carlsbad": "America/Los_Angeles",
    "carson": "America/Los_Angeles",
    "calabasas": "America/Los_Angeles",
    "tiburon": "America/Los_Angeles",
    "fairfield": "America/Los_Angeles",
    "aptos": "America/Los_Angeles",
    "stockton": "America/Los_Angeles",
    "napa": "America/Los_Angeles",
    "phoenix": "America/Phoenix",
    "tempe": "America/Phoenix",
    "las vegas": "America/Los_Angeles",
    "honolulu": "Pacific/Honolulu",
    "maui": "Pacific/Honolulu",
    "orlando": "America/New_York",
    "ann arbor": "America/New_York",
    "binghamton": "America/New_York",
    "sunrise": "America/New_York",
    "happy valley": "America/New_York",
    "winnetka": "America/Chicago",
    # Australia
    "melbourne": "Australia/Melbourne",
    "sydney": "Australia/Sydney",
    "brisbane": "Australia/Brisbane",
    "adelaide": "Australia/Adelaide",
    "perth": "Australia/Perth",
    "perth-sydney": "Australia/Sydney",
    "sydney + perth": "Australia/Sydney",
    "hobart": "Australia/Hobart",
    "canberra": "Australia/Sydney",
    "burnie": "Australia/Hobart",
    "bendigo": "Australia/Melbourne",
    "playford": "Australia/Adelaide",
    "caloundra": "Australia/Brisbane",
    "traralgon": "Australia/Melbourne",
    # Canada
    "toronto": "America/Toronto",
    "montreal": "America/Toronto",
    "quebec city": "America/Toronto",
    "granby": "America/Toronto",
    "rimouski": "America/Toronto",
    "drummondville": "America/Toronto",
    "gatineau": "America/Toronto",
    "vancouver": "America/Vancouver",
    "calgary": "America/Edmonton",
    "winnipeg": "America/Winnipeg",
    # Russia
    "moscow": "Europe/Moscow",
    "st. petersburg": "Europe/Moscow",
    "kazan": "Europe/Moscow",
    "penza": "Europe/Moscow",
    "saransk": "Europe/Moscow",
    "lermontov": "Europe/Moscow",
    "tyumen": "Asia/Yekaterinburg",
    # Brazil
    "sao paulo": "America/Sao_Paulo",
    "são paulo": "America/Sao_Paulo",
    "rio de janeiro": "America/Sao_Paulo",
    "rio quente": "America/Sao_Paulo",
    "florianopolis": "America/Sao_Paulo",
    "curitiba": "America/Sao_Paulo",
    "campinas": "America/Sao_Paulo",
    "piracicaba": "America/Sao_Paulo",
    "porto alegre": "America/Sao_Paulo",
    "potro alegre": "America/Sao_Paulo",
    "itajai": "America/Sao_Paulo",
    "sao leopoldo": "America/Sao_Paulo",
    "santos": "America/Sao_Paulo",
    "sao jose do rio preto": "America/Sao_Paulo",
    "campos do jordao": "America/Sao_Paulo",
    "belo horizonte": "America/Sao_Paulo",
    "brasilia": "America/Sao_Paulo",
    "salvador": "America/Bahia",
    "salvador de bahia": "America/Bahia",
    "recife": "America/Recife",
    "belem": "America/Belem",
    "costa do sauipe": "America/Bahia",
    # Mexico
    "acapulco": "America/Mexico_City",
    "guadalajara": "America/Mexico_City",
    "mexico city": "America/Mexico_City",
    "monterrey": "America/Monterrey",
    "cancun": "America/Cancun",
    "puerto vallarta": "America/Mexico_City",
    "san luis potosi": "America/Mexico_City",
    "merida": "America/Merida",
    "mérida": "America/Merida",
    "morelia": "America/Mexico_City",
    "queretaro": "America/Mexico_City",
    "morelos": "America/Mexico_City",
    "manzanillo": "America/Mexico_City",
    "tampico": "America/Monterrey",
    "los cabos": "America/Mazatlan",
    "aguascalientes": "America/Mexico_City",
    "leon": "America/Mexico_City",
    "metepec": "America/Mexico_City",
    "puebla": "America/Mexico_City",
    # Cities without country that we can identify
    "hong kong": "Asia/Hong_Kong",
    "singapore": "Asia/Singapore",
    "bangkok": "Asia/Bangkok",
    "doha": "Asia/Qatar",
    "dubai": "Asia/Dubai",
    "abu dhabi": "Asia/Dubai",
    "fujairah": "Asia/Dubai",
    "jeddah": "Asia/Riyadh",
    "riyadh": "Asia/Riyadh",
    "manama": "Asia/Bahrain",
    "tel aviv": "Asia/Jerusalem",
    "jerusalem": "Asia/Jerusalem",
    "raanana": "Asia/Jerusalem",
    "ramat hasharon": "Asia/Jerusalem",
    "cairo": "Africa/Cairo",
    "rabat": "Africa/Casablanca",
    "casablanca": "Africa/Casablanca",
    "marrakech": "Africa/Casablanca",
    "kenitra": "Africa/Casablanca",
    "mohammedia": "Africa/Casablanca",
    "meknes": "Africa/Casablanca",
    "tanger": "Africa/Casablanca",
    "tunis": "Africa/Tunis",
    "monastir": "Africa/Tunis",
    "johannesburg": "Africa/Johannesburg",
    "potchefstroom": "Africa/Johannesburg",
    "abidjan": "Africa/Abidjan",
    "kigali": "Africa/Kigali",
    "brazzaville": "Africa/Brazzaville",
    "soma bay": "Africa/Cairo",
    "taipei": "Asia/Taipei",
    "kaohsiung": "Asia/Taipei",
    "kuala lumpur": "Asia/Kuala_Lumpur",
    "manila": "Asia/Manila",
    "ho chi minh city": "Asia/Ho_Chi_Minh",
    "da nang": "Asia/Ho_Chi_Minh",
    "phan thiet": "Asia/Ho_Chi_Minh",
    "kolkata": "Asia/Kolkata",
    "bangalore": "Asia/Kolkata",
    "bengaluru": "Asia/Kolkata",
    "mumbai": "Asia/Kolkata",
    "new delhi": "Asia/Kolkata",
    "indore": "Asia/Kolkata",
    "pune": "Asia/Kolkata",
    "chennai": "Asia/Kolkata",
    "islamabad": "Asia/Karachi",
    # European cities without country
    "paris": "Europe/Paris",
    "london": "Europe/London",
    "wimbledon": "Europe/London",
    "berlin": "Europe/Berlin",
    "rome": "Europe/Rome",
    "madrid": "Europe/Madrid",
    "barcelona": "Europe/Madrid",
    "vienna": "Europe/Vienna",
    "budapest": "Europe/Budapest",
    "bucharest": "Europe/Bucharest",
    "brussels": "Europe/Brussels",
    "antwerp": "Europe/Brussels",
    "amsterdam": "Europe/Amsterdam",
    "prague": "Europe/Prague",
    "warsaw": "Europe/Warsaw",
    "copenhagen": "Europe/Copenhagen",
    "stockholm": "Europe/Stockholm",
    "helsinki": "Europe/Helsinki",
    "oslo": "Europe/Oslo",
    "lisbon": "Europe/Lisbon",
    "athens": "Europe/Athens",
    "istanbul": "Europe/Istanbul",
    "instanbul": "Europe/Istanbul",
    "belgrade": "Europe/Belgrade",
    "zagreb": "Europe/Zagreb",
    "sofia": "Europe/Sofia",
    "ljubljana": "Europe/Ljubljana",
    "bratislava": "Europe/Bratislava",
    "tallinn": "Europe/Tallinn",
    "vilnius": "Europe/Vilnius",
    "riga": "Europe/Riga",
    "baku": "Asia/Baku",
    "tbilisi": "Asia/Tbilisi",
    "kyiv": "Europe/Kiev",
    "chisinau": "Europe/Chisinau",
    "skopje": "Europe/Skopje",
    "sarajevo": "Europe/Sarajevo",
    "monaco": "Europe/Monaco",
    "monte-carlo": "Europe/Monaco",
    # Other well-known cities without country
    "lima": "America/Lima",
    "bogota": "America/Bogota",
    "santiago": "America/Santiago",
    "buenos aires": "America/Argentina/Buenos_Aires",
    "cordoba": "America/Argentina/Cordoba",
    "montevideo": "America/Montevideo",
    "asuncion": "America/Asuncion",
    "quito": "America/Guayaquil",
    "guayaquil": "America/Guayaquil",
    "cali": "America/Bogota",
    "barranquilla": "America/Bogota",
    "medellin": "America/Bogota",
    "santa cruz": "America/La_Paz",
    "santa cruz de la sierra": "America/La_Paz",
    "panama city": "America/Panama",
    "santo domingo": "America/Santo_Domingo",
    "cap cana": "America/Santo_Domingo",
    "san juan": "America/Puerto_Rico",
    "palmas del mar": "America/Puerto_Rico",
    "le gosier": "America/Guadeloupe",
    # Asian cities without country
    "tokyo": "Asia/Tokyo",
    "osaka": "Asia/Tokyo",
    "kobe": "Asia/Tokyo",
    "yokohama": "Asia/Tokyo",
    "yokkaichi": "Asia/Tokyo",
    "matsuyama": "Asia/Tokyo",
    "kyoto": "Asia/Tokyo",
    "toyota": "Asia/Tokyo",
    "seoul": "Asia/Seoul",
    "busan": "Asia/Seoul",
    "gwangju": "Asia/Seoul",
    "gimcheon": "Asia/Seoul",
    "yeongwol": "Asia/Seoul",
    "beijing": "Asia/Shanghai",
    "shanghai": "Asia/Shanghai",
    "shenzhen": "Asia/Shanghai",
    "guangzhou": "Asia/Shanghai",
    "chengdu": "Asia/Shanghai",
    "wuhan": "Asia/Shanghai",
    "hangzhou": "Asia/Shanghai",
    "nanjing": "Asia/Shanghai",
    "tianjin": "Asia/Shanghai",
    "suzhou": "Asia/Shanghai",
    "jinan": "Asia/Shanghai",
    "ningbo": "Asia/Shanghai",
    "changsha": "Asia/Shanghai",
    "zhengzhou": "Asia/Shanghai",
    "wuxi": "Asia/Shanghai",
    "zhuhai": "Asia/Shanghai",
    "qingdao": "Asia/Shanghai",
    "jingshan": "Asia/Shanghai",
    "anning": "Asia/Shanghai",
    "kun-ming": "Asia/Shanghai",
    "pingguo": "Asia/Shanghai",
    "nanchang": "Asia/Shanghai",
    "baotou": "Asia/Shanghai",
    "quanzhou": "Asia/Shanghai",
    "liuzhou": "Asia/Shanghai",
    "jiujiang": "Asia/Shanghai",
    "zhangjiagang": "Asia/Shanghai",
    "huzhou": "Asia/Shanghai",
    "wuhai": "Asia/Shanghai",
    "qujing": "Asia/Shanghai",
    "almaty": "Asia/Almaty",
    "nur-sultan": "Asia/Almaty",
    "astana": "Asia/Almaty",
    "shymkent": "Asia/Almaty",
    "tashkent": "Asia/Tashkent",
    "samarkand": "Asia/Samarkand",
    "karshi": "Asia/Tashkent",
    "fergana": "Asia/Tashkent",
    "hua hin": "Asia/Bangkok",
    "pattaya": "Asia/Bangkok",
    "nonthaburi": "Asia/Bangkok",
    "auckland": "Pacific/Auckland",
    "noumea": "Pacific/Noumea",
    "reunion island": "Indian/Reunion",
    # Obscure cities without country
    "salinas": "America/Guayaquil",  # Ecuador
    "forli": "Europe/Rome",
    "kachreti": "Asia/Tbilisi",  # Georgia
    "batman": "Europe/Istanbul",  # Turkey
    "manta": "America/Guayaquil",  # Ecuador
    "petange": "Europe/Luxembourg",
    "ojai": "America/Los_Angeles",  # California
    "aachen": "Europe/Berlin",
    # European cities without country (additional)
    "malaga": "Europe/Madrid",
    "marbella": "Europe/Madrid",
    "cologne": "Europe/Berlin",
    "dortmund": "Europe/Berlin",
    "dusseldorf": "Europe/Berlin",
    "wolfsburg": "Europe/Berlin",
    "heilbronn": "Europe/Berlin",
    "marburg": "Europe/Berlin",
    "furth": "Europe/Berlin",
    "augsburg": "Europe/Berlin",
    "karlsruhe": "Europe/Berlin",
    "braunschweig": "Europe/Berlin",
    "koblenz": "Europe/Berlin",
    "ludwigshafen": "Europe/Berlin",
    "luedenscheid": "Europe/Berlin",
    "troisdorf": "Europe/Berlin",
    "meerbusch": "Europe/Berlin",
    "oberstaufen": "Europe/Berlin",
    "eckental": "Europe/Berlin",
    "ismaning": "Europe/Berlin",
    "pullach": "Europe/Berlin",
    "bad homburg": "Europe/Berlin",
    "nürnberg": "Europe/Berlin",
    "lyon": "Europe/Paris",
    "marseille": "Europe/Paris",
    "toulouse": "Europe/Paris",
    "bordeaux": "Europe/Paris",
    "nice": "Europe/Paris",
    "strasbourg": "Europe/Paris",
    "rennes": "Europe/Paris",
    "lille": "Europe/Paris",
    "metz": "Europe/Paris",
    "montpellier": "Europe/Paris",
    "rouen": "Europe/Paris",
    "pau": "Europe/Paris",
    "angers": "Europe/Paris",
    "brest": "Europe/Paris",
    "blois": "Europe/Paris",
    "limoges": "Europe/Paris",
    "troyes": "Europe/Paris",
    "quimper": "Europe/Paris",
    "orleans": "Europe/Paris",
    "aix-en-provence": "Europe/Paris",
    "cassis": "Europe/Paris",
    "sophia antipolis": "Europe/Paris",
    "saint-tropez": "Europe/Paris",
    "contrexeville": "Europe/Paris",
    "roanne": "Europe/Paris",
    "cherbourg": "Europe/Paris",
    "thionville": "Europe/Paris",
    "saint malo": "Europe/Paris",
    "mouilleron le captif": "Europe/Paris",
    "royan": "Europe/Paris",
    "st. brieuc": "Europe/Paris",
    "les sables d'olonne": "Europe/Paris",
    "st. remy": "Europe/Paris",
    "naples": "Europe/Rome",
    "napoli": "Europe/Rome",
    "palermo": "Europe/Rome",
    "florence": "Europe/Rome",
    "cagliari": "Europe/Rome",
    "parma": "Europe/Rome",
    "milan": "Europe/Rome",
    "turin": "Europe/Rome",
    "bergamo": "Europe/Rome",
    "verona": "Europe/Rome",
    "trieste": "Europe/Rome",
    "genoa": "Europe/Rome",
    "monza": "Europe/Rome",
    "como": "Europe/Rome",
    "perugia": "Europe/Rome",
    "modena": "Europe/Rome",
    "brescia": "Europe/Rome",
    "padova": "Europe/Rome",
    "bari": "Europe/Rome",
    "rimini": "Europe/Rome",
    "olbia": "Europe/Rome",
    "sardinia": "Europe/Rome",
    "biella": "Europe/Rome",
    "sassuolo": "Europe/Rome",
    "rovereto": "Europe/Rome",
    "vicenza": "Europe/Rome",
    "tolentino": "Europe/Rome",
    "francavilla al mare": "Europe/Rome",
    "grado": "Europe/Rome",
    "todi": "Europe/Rome",
    "cesenatico": "Europe/Rome",
    "barletta": "Europe/Rome",
    "reggio emilia": "Europe/Rome",
    "vercelli": "Europe/Rome",
    "rende": "Europe/Rome",
    "caltanissetta": "Europe/Rome",
    "ortisei": "Europe/Rome",
    "san benedetto del tronto": "Europe/Rome",
    "orbetello": "Europe/Rome",
    "alessandria": "Europe/Rome",
    "recanati": "Europe/Rome",
    "roseto degli abruzzi": "Europe/Rome",
    "l'aquila": "Europe/Rome",
    "trani": "Europe/Rome",
    "cordenons": "Europe/Rome",
    "gaiba": "Europe/Rome",
    "fano": "Europe/Rome",
    "mestre": "Europe/Rome",
    "manerbio": "Europe/Rome",
    "cremona": "Europe/Rome",
    "courmayeur": "Europe/Rome",
    "andria": "Europe/Rome",
    "sanremo": "Europe/Rome",
    "san remo": "Europe/Rome",
    "cortina": "Europe/Rome",
    "oeiras": "Europe/Lisbon",
    "oeiras (estoril)": "Europe/Lisbon",
    "estoril": "Europe/Lisbon",
    "porto": "Europe/Lisbon",
    "braga": "Europe/Lisbon",
    "maia": "Europe/Lisbon",
    "caldas da rainha": "Europe/Lisbon",
    "guimaraes": "Europe/Lisbon",
    "rotterdam": "Europe/Amsterdam",
    "'s-hertogenbosch": "Europe/Amsterdam",
    "s-hertogenbosch": "Europe/Amsterdam",
    "alphen": "Europe/Amsterdam",
    "scheveningen": "Europe/Amsterdam",
    "amersfoort": "Europe/Amsterdam",
    "basel": "Europe/Zurich",
    "geneva": "Europe/Zurich",
    "lugano": "Europe/Zurich",
    "lausanne": "Europe/Zurich",
    "gstaad": "Europe/Zurich",
    "biel": "Europe/Zurich",
    "montreux": "Europe/Zurich",
    "zug": "Europe/Zurich",
    "kitzbuhel": "Europe/Vienna",
    "bad waltersdorf": "Europe/Vienna",
    "bad gastein": "Europe/Vienna",
    "linz": "Europe/Vienna",
    "salzburg": "Europe/Vienna",
    "mauthausen": "Europe/Vienna",
    "tulln": "Europe/Vienna",
    "bastad": "Europe/Stockholm",
    "jonkoping": "Europe/Stockholm",
    "danderyd": "Europe/Stockholm",
    "umag": "Europe/Zagreb",
    "split": "Europe/Zagreb",
    "zadar": "Europe/Zagreb",
    "makarska": "Europe/Zagreb",
    "rijeka": "Europe/Zagreb",
    "losinj": "Europe/Zagreb",
    "ostrava": "Europe/Prague",
    "liberec": "Europe/Prague",
    "prostejov": "Europe/Prague",
    "kosice": "Europe/Bratislava",
    "trnava": "Europe/Bratislava",
    "iasi": "Europe/Bucharest",
    "brasov": "Europe/Bucharest",
    "targu mures": "Europe/Bucharest",
    "cluj-napoca": "Europe/Bucharest",
    "sibiu": "Europe/Bucharest",
    "timisoara": "Europe/Bucharest",
    "katowice": "Europe/Warsaw",
    "szczecin": "Europe/Warsaw",
    "grodzisk mazowiecki": "Europe/Warsaw",
    "poznan": "Europe/Warsaw",
    "wroclaw": "Europe/Warsaw",
    "bytom": "Europe/Warsaw",
    "sopot": "Europe/Warsaw",
    "hersonissos": "Europe/Athens",
    "rhodes": "Europe/Athens",
    "antalya": "Europe/Istanbul",
    "samsun": "Europe/Istanbul",
    "eskisehir": "Europe/Istanbul",
    "mersin": "Europe/Istanbul",
    "agri": "Europe/Istanbul",
    "izmir": "Europe/Istanbul",
    "portoroz": "Europe/Ljubljana",
    "szekesfehevar": "Europe/Budapest",
    "mons": "Europe/Brussels",
    "ottignies-louvain-la-neuve": "Europe/Brussels",
    "bercuit": "Europe/Brussels",
    "eastbourne": "Europe/London",
    "nottingham": "Europe/London",
    "birmingham": "Europe/London",
    "surbiton": "Europe/London",
    "ilkley": "Europe/London",
    "loughborough": "Europe/London",
    "bath": "Europe/London",
    "glasgow": "Europe/London",
    "manchester": "Europe/London",
    "jersey": "Europe/London",
    "gran canaria": "Atlantic/Canary",
    "tenerife": "Atlantic/Canary",
    "maspalomas": "Atlantic/Canary",
    "mallorca": "Europe/Madrid",
    "menorca": "Europe/Madrid",
    "manacor": "Europe/Madrid",
    "valencia": "Europe/Madrid",
    "seville": "Europe/Madrid",
    "san sebastian": "Europe/Madrid",
    "girona": "Europe/Madrid",
    "lleida": "Europe/Madrid",
    "murcia": "Europe/Madrid",
    "tarragona": "Europe/Madrid",
    "pozoblanco": "Europe/Madrid",
    "segovia": "Europe/Madrid",
    "villena": "Europe/Madrid",
    "gijon": "Europe/Madrid",
    "la bisbal d'empordá": "Europe/Madrid",
    "las franquesas del valles": "Europe/Madrid",
    "banja luka": "Europe/Sarajevo",
    "arad": "Europe/Bucharest",
    "dobrich": "Europe/Sofia",
    # South American cities without country
    "tucuman": "America/Argentina/Tucuman",
    "san miguel de tucuman": "America/Argentina/Tucuman",
    "rosario": "America/Argentina/Buenos_Aires",
    "corrientes": "America/Argentina/Cordoba",
    "mendoza": "America/Argentina/Mendoza",
    "villa maria": "America/Argentina/Cordoba",
    "santa fe": "America/Argentina/Cordoba",
    "villa allende": "America/Argentina/Cordoba",
    "vina del mar": "America/Santiago",
    "montemar": "America/Santiago",
    "concepcion": "America/Santiago",
    "temuco": "America/Santiago",
    "colina": "America/Santiago",
    "antofagasta": "America/Santiago",
    "coquimbo": "America/Santiago",
    "punta del este": "America/Montevideo",
    "ibague": "America/Bogota",
    "floridablanca": "America/Bogota",
    "pereira": "America/Bogota",
    "ambato": "America/Guayaquil",
    "machala": "America/Guayaquil",
    "olimpia": "America/Sao_Paulo",
    "santo domingo": "America/Santo_Domingo",
    "chitre": "America/Panama",
}


def lookup_timezone(city: str | None, country: str | None) -> str | None:
    """Look up timezone from static mappings. No external API calls."""
    if not city:
        return None

    city_lower = city.strip().lower()

    # Try city-level override first (handles multi-timezone countries + no-country entries)
    tz = CITY_TIMEZONE_OVERRIDES.get(city_lower)
    if tz:
        return tz

    # Try country mapping
    if country:
        tz = COUNTRY_TO_TIMEZONE.get(country.strip())
        if tz:
            return tz

    # Try to resolve country from city using existing geo utility
    resolved_country = city_to_country(city)
    if resolved_country:
        tz = COUNTRY_TO_TIMEZONE.get(resolved_country)
        if tz:
            return tz

    return None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    with get_session() as session:
        tournaments = session.execute(
            select(Tournament).where(
                Tournament.city.isnot(None),
                Tournament.timezone.is_(None),
            )
        ).scalars().all()

        logger.info("Found %d tournaments to backfill", len(tournaments))
        updated = 0
        failed = 0

        for t in tournaments:
            tz = lookup_timezone(t.city, t.country)
            if tz:
                t.timezone = tz
                updated += 1
                logger.info("  %-30s %-20s -> %s", t.city, t.country or "(no country)", tz)
            else:
                failed += 1
                logger.warning("  %-30s %-20s -> FAILED", t.city, t.country or "(no country)")

        logger.info("\nUpdated: %d, Failed: %d", updated, failed)

        if args.dry_run:
            logger.info("Dry run — rolling back")
            session.rollback()
        else:
            session.commit()
            logger.info("Committed")


if __name__ == "__main__":
    main()
