"""
Geographic lookup utilities for tennis data.

This module provides mappings and helper functions to normalize country names,
convert cities to countries, and look up IOC (International Olympic Committee)
country codes. This is essential for standardizing location data from different
sources (ATP, WTA, ITF, betting sites) which may use different naming conventions.
"""

from typing import Optional

# Comprehensive mapping of country names to 3-letter IOC codes.
# Includes common variations and alternate spellings found in tennis data.
COUNTRY_TO_IOC: dict[str, str] = {
    "Albania": "ALB",
    "Algeria": "ALG",
    "Andorra": "AND",
    "Argentina": "ARG",
    "Australia": "AUS",
    "Austria": "AUT",
    "Bahamas": "BAH",
    "Bahrain": "BRN",
    "Bangladesh": "BAN",
    "Barbados": "BAR",
    "Belarus": "BLR",
    "Belgium": "BEL",
    "Benin": "BEN",
    "Bolivia": "BOL",
    "Bosnia": "BIH",
    "Bosnia and Herzegovina": "BIH",
    "Brazil": "BRA",
    "Britain": "GBR",
    "Bulgaria": "BUL",
    "Burkina Faso": "BUR",
    "Cambodia": "CAM",
    "Cameroon": "CMR",
    "Canada": "CAN",
    "Chad": "CHA",
    "Chile": "CHI",
    "China": "CHN",
    "Chinese Taipei": "TPE",
    "Colombia": "COL",
    "Congo": "CGO",
    "Costa Rica": "CRC",
    "Cote d'Ivoire": "CIV",
    "Croatia": "CRO",
    "Cuba": "CUB",
    "Cyprus": "CYP",
    "Czech Republic": "CZE",
    "Czechia": "CZE",
    "DR Congo": "COD",
    "Democratic Republic of the Congo": "COD",
    "Denmark": "DEN",
    "Dominican Republic": "DOM",
    "Ecuador": "ECU",
    "Egypt": "EGY",
    "El Salvador": "ESA",
    "England": "GBR",
    "Estonia": "EST",
    "Ethiopia": "ETH",
    "Finland": "FIN",
    "France": "FRA",
    "Georgia": "GEO",
    "Germany": "GER",
    "Ghana": "GHA",
    "Great Britain": "GBR",
    "Greece": "GRE",
    "Guatemala": "GUA",
    "Haiti": "HAI",
    "Honduras": "HON",
    "Hong Kong": "HKG",
    "Hungary": "HUN",
    "Iceland": "ISL",
    "India": "IND",
    "Indonesia": "INA",
    "Iran": "IRI",
    "Iraq": "IRQ",
    "Ireland": "IRL",
    "Israel": "ISR",
    "Italy": "ITA",
    "Ivory Coast": "CIV",
    "Jamaica": "JAM",
    "Japan": "JPN",
    "Jordan": "JOR",
    "Kazakhstan": "KAZ",
    "Kenya": "KEN",
    "Kosovo": "KOS",
    "Kuwait": "KUW",
    "Laos": "LAO",
    "Latvia": "LAT",
    "Lebanon": "LBN",
    "Liechtenstein": "LIE",
    "Lithuania": "LTU",
    "Luxembourg": "LUX",
    "Madagascar": "MAD",
    "Malaysia": "MAS",
    "Mali": "MLI",
    "Malta": "MLT",
    "Mexico": "MEX",
    "Moldova": "MDA",
    "Monaco": "MON",
    "Mongolia": "MGL",
    "Montenegro": "MNE",
    "Morocco": "MAR",
    "Mozambique": "MOZ",
    "Myanmar": "MYA",
    "Nepal": "NEP",
    "Netherlands": "NED",
    "New Zealand": "NZL",
    "Niger": "NIG",
    "Nigeria": "NGR",
    "North Korea": "PRK",
    "North Macedonia": "MKD",
    "Norway": "NOR",
    "Oman": "OMA",
    "Pakistan": "PAK",
    "Panama": "PAN",
    "Paraguay": "PAR",
    "Peru": "PER",
    "Philippines": "PHI",
    "Poland": "POL",
    "Portugal": "POR",
    "Puerto Rico": "PUR",
    "Qatar": "QAT",
    "Romania": "ROU",
    "Russia": "RUS",
    "Rwanda": "RWA",
    "San Marino": "SMR",
    "Saudi Arabia": "KSA",
    "Scotland": "GBR",
    "Senegal": "SEN",
    "Serbia": "SRB",
    "Singapore": "SGP",
    "Slovakia": "SVK",
    "Slovenia": "SLO",
    "South Africa": "RSA",
    "South Korea": "KOR",
    "Spain": "ESP",
    "Sri Lanka": "SRI",
    "Sweden": "SWE",
    "Switzerland": "SUI",
    "Taiwan": "TPE",
    "Tanzania": "TAN",
    "Thailand": "THA",
    "Togo": "TOG",
    "Trinidad and Tobago": "TTO",
    "Tunisia": "TUN",
    "Turkey": "TUR",
    "UAE": "UAE",
    "Uganda": "UGA",
    "Ukraine": "UKR",
    "United Arab Emirates": "UAE",
    "United Kingdom": "GBR",
    "United States": "USA",
    "Uruguay": "URU",
    "USA": "USA",
    "Uzbekistan": "UZB",
    "Venezuela": "VEN",
    "Vietnam": "VIE",
    "Wales": "GBR",
    "Zimbabwe": "ZIM",
}

# Mapping of tennis tournament cities to their country names.
# Keys match city names in our database, values must exist in COUNTRY_TO_IOC keys.
CITY_TO_COUNTRY: dict[str, str] = {
    "'s-Hertogenbosch": "Netherlands",
    "Abidjan": "Ivory Coast",
    "Acapulco": "Mexico",
    "Adelaide": "Australia",
    "Aix-en-Provence": "France",
    "Almaty": "Kazakhstan",
    "Antofagasta": "Chile",
    "Astana": "Kazakhstan",
    "Asuncion": "Paraguay",
    "Athens": "Greece",
    "Atlanta": "United States",
    "Auckland": "New Zealand",
    "Augsburg": "Germany",
    "Bad Waltersdorf": "Austria",
    "Barcelona": "Spain",
    "Barletta": "Italy",
    "Barranquilla": "Colombia",
    "Basel": "Switzerland",
    "Bastad": "Sweden",
    "Beijing": "China",
    "Belgrade": "Serbia",
    "Bengaluru": "India",
    "Bergamo": "Italy",
    "Biella": "Italy",
    "Birmingham": "United Kingdom",
    "Blois": "France",
    "Bloomfield Hills": "United States",
    "Bogota": "Colombia",
    "Bologna": "Italy",
    "Bonn": "Germany",
    "Bordeaux": "France",
    "Braga": "Portugal",
    "Brasov": "Romania",
    "Bratislava": "Slovakia",
    "Braunschweig": "Germany",
    "Brazzaville": "Congo",
    "Brest": "France",
    "Brisbane": "Australia",
    "Brussels": "Belgium",
    "Bucharest": "Romania",
    "Buenos Aires": "Argentina",
    "Bunschoten": "Netherlands",
    "Burnie": "Australia",
    "Busan": "South Korea",
    "Cagliari": "Italy",
    "Calgary": "Canada",
    "Cali": "Colombia",
    "Campinas": "Brazil",
    "Canberra": "Australia",
    "Cancun": "Mexico",
    "Cap Cana": "Dominican Republic",
    "Cary": "United States",
    "Cassis": "France",
    "Cesenatico": "Italy",
    "Champaign": "United States",
    "Charleston": "United States",
    "Charlottesville": "United States",
    "Chengdu": "China",
    "Chennai": "India",
    "Cherbourg": "France",
    "Chicago": "United States",
    "Chisinau": "Moldova",
    "Cincinnati": "United States",
    "Cleveland": "United States",
    "Columbus": "United States",
    "Como": "Italy",
    "Concepcion": "Chile",
    "Cordenons": "Italy",
    "Cordoba": "Argentina",
    "Costa do Sauipe": "Brazil",
    "Curitiba": "Brazil",
    "Dallas": "United States",
    "Delray Beach": "United States",
    "Doha": "Qatar",
    "Drummondville": "Canada",
    "Dubai": "UAE",
    "Eastbourne": "United Kingdom",
    "Estoril": "Portugal",
    "Fairfield": "United States",
    "Florianopolis": "Brazil",
    "Francavilla al Mare": "Italy",
    "Geneva": "Switzerland",
    "Genoa": "Italy",
    "Girona": "Spain",
    "Glasgow": "United Kingdom",
    "Granby": "Canada",
    "Grodzisk Mazowiecki": "Poland",
    "Gstaad": "Switzerland",
    "Guangzhou": "China",
    "Guayaquil": "Ecuador",
    "Gwangju": "South Korea",
    "Hagen": "Germany",
    "Halle": "Germany",
    "Hamburg": "Germany",
    "Hangzhou": "China",
    "Heilbronn - Bad Rappenau": "Germany",
    "Helsinki": "Finland",
    "Hersonissos": "Greece",
    "Hong Kong": "China",
    "Houston": "United States",
    "Iasi": "Romania",
    "Ibague": "Colombia",
    "Ilkley": "United Kingdom",
    "Indian Wells": "United States",
    "Islamabad": "Pakistan",
    "Istanbul": "Turkey",
    "Itajai": "Brazil",
    "Jeddah": "Saudi Arabia",
    "Jinan": "China",
    "Jingshan": "China",
    "Karlsruhe": "Germany",
    "Kigali": "Rwanda",
    "Kitzbuhel": "Austria",
    "Knoxville": "United States",
    "Kobe": "Japan",
    "Koblenz": "Germany",
    "Las Vegas": "United States",
    "Lexington": "United States",
    "Liberec": "Czech Republic",
    "Lille": "France",
    "Lima": "Peru",
    "Lincoln": "United States",
    "Lisbon": "Portugal",
    "Little Rock": "United States",
    "London": "United Kingdom",
    "Los Cabos": "Mexico",
    "Lugano": "Switzerland",
    "Lyon": "France",
    "Madrid": "Spain",
    "Maia": "Portugal",
    "Mallorca": "Spain",
    "Manacor": "Spain",
    "Manama": "Bahrain",
    "Manzanillo": "Mexico",
    "Marrakech": "Morocco",
    "Marseille": "France",
    "Matsuyama": "Japan",
    "Mauthausen": "Austria",
    "Melbourne": "Australia",
    "Menorca": "Spain",
    "Merida": "Mexico",
    "Metz": "France",
    "Mexico City": "Mexico",
    "Miami": "United States",
    "Milan": "Italy",
    "Modena": "Italy",
    "Monastir": "Tunisia",
    "Monte-Carlo": "Monaco",
    "Montemar": "Chile",
    "Montevideo": "Uruguay",
    "Montpellier": "France",
    "Montreal": "Canada",
    "Monza": "Italy",
    "Morelia": "Mexico",
    "Morelos": "Mexico",
    "Mouilleron le Captif": "France",
    "Munich": "Germany",
    "Murcia": "Spain",
    "Naples": "Italy",
    "New Delhi": "India",
    "New York": "United States",
    "Newport": "United States",
    "Nonthaburi": "Thailand",
    "Nottingham": "United Kingdom",
    "Noumea": "France",
    "Oeiras": "Portugal",
    "Olbia": "Italy",
    "Orleans": "France",
    "Ostrava": "Czech Republic",
    "Ottignies-Louvain-La-Neuve": "Belgium",
    "Paris": "France",
    "Pau": "France",
    "Perth-Sydney": "Australia",
    "Perugia": "Italy",
    "Phan Thiet": "Vietnam",
    "Phoenix": "United States",
    "Piracicaba": "Brazil",
    "Playford": "Australia",
    "Porto": "Portugal",
    "Porto Alegre": "Brazil",
    "Poznan": "Poland",
    "Pozoblanco": "Spain",
    "Prague": "Czech Republic",
    "Prostejov": "Czech Republic",
    "Puerto Vallarta": "Mexico",
    "Pune": "India",
    "Punta del Este": "Uruguay",
    "Quimper": "France",
    "Rennes": "France",
    "Rio de Janeiro": "Brazil",
    "Roanne": "France",
    "Rome": "Italy",
    "Rosario": "Argentina",
    "Rotterdam": "Netherlands",
    "Rovereto": "Italy",
    "Royan": "France",
    "Saint-Tropez": "France",
    "Salzburg": "Austria",
    "San Diego": "United States",
    "San Luis Potosi": "Mexico",
    "San Marino": "San Marino",
    "San Miguel de Tucuman": "Argentina",
    "Santa Cruz": "Bolivia",
    "Santa Cruz De La Sierra": "Bolivia",
    "Santa Fe": "Argentina",
    "Santiago": "Chile",
    "Santo Domingo": "Dominican Republic",
    "Santos": "Brazil",
    "Sao Leopoldo": "Brazil",
    "São Paulo": "Brazil",
    "Sarasota": "United States",
    "Sassuolo": "Italy",
    "Savannah": "United States",
    "Segovia": "Spain",
    "Seoul": "South Korea",
    "Seville": "Spain",
    "Shanghai": "China",
    "Shenzhen": "China",
    "Sibiu": "Romania",
    "Sioux Falls": "United States",
    "Skopje": "North Macedonia",
    "Sofia": "Bulgaria",
    "Soma Bay": "Egypt",
    "Split": "Croatia",
    "St. Brieuc": "France",
    "Stockholm": "Sweden",
    "Stuttgart": "Germany",
    "Sumter": "United States",
    "Surbiton": "United Kingdom",
    "Suzhou": "China",
    "Sydney": "Australia",
    "Szczecin": "Poland",
    "Szekesfehevar": "Hungary",
    "Taipei": "Taiwan",
    "Tallahassee": "United States",
    "Tampere": "Finland",
    "Targu Mures": "Romania",
    "Tbilisi": "Georgia",
    "Temuco": "Chile",
    "Tenerife": "Spain",
    "Thionville": "France",
    "Tiburon": "United States",
    "Todi": "Italy",
    "Tokyo": "Japan",
    "Trieste": "Italy",
    "Troyes": "France",
    "Tulln": "Austria",
    "Tunis": "Tunisia",
    "Turin": "Italy",
    "Tyler": "United States",
    "Umag": "Croatia",
    "Valencia": "Spain",
    "Verona": "Italy",
    "Vicenza": "Italy",
    "Vienna": "Austria",
    "Villa Maria": "Argentina",
    "Villena": "Spain",
    "Washington": "United States",
    "Winnipeg": "Canada",
    "Winston Salem": "United States",
    "Winston-Salem": "United States",
    "Wuxi": "China",
    "Yokkaichi": "Japan",
    "Yokohama": "Japan",
    "Zadar": "Croatia",
    "Zagreb": "Croatia",
    "Zhangjiagang": "China",
    "Zug": "Switzerland",
}

# Lookup caches (lazy initialization for case-insensitive matching)
_LOWER_COUNTRY_TO_IOC: Optional[dict[str, str]] = None
_LOWER_CITY_TO_COUNTRY: Optional[dict[str, str]] = None


def country_to_ioc(country_name: str) -> Optional[str]:
    """
    Look up IOC code for a country name. Case-insensitive.

    Args:
        country_name: Name of the country (e.g., "United States", "spain")

    Returns:
        3-letter IOC code (e.g., "USA", "ESP") or None if not found.
    """
    if not country_name:
        return None

    # Check exact match first (fastest path)
    if country_name in COUNTRY_TO_IOC:
        return COUNTRY_TO_IOC[country_name]

    global _LOWER_COUNTRY_TO_IOC
    if _LOWER_COUNTRY_TO_IOC is None:
        _LOWER_COUNTRY_TO_IOC = {k.lower(): v for k, v in COUNTRY_TO_IOC.items()}

    normalized = country_name.strip().lower()
    return _LOWER_COUNTRY_TO_IOC.get(normalized)


def city_to_country(city: str) -> Optional[str]:
    """
    Look up country name for a tennis city. Case-insensitive.

    Args:
        city: Name of the city (e.g., "Paris", "london")

    Returns:
        Country name matching a key in COUNTRY_TO_IOC, or None if not found.
    """
    if not city:
        return None

    # Check exact match first
    if city in CITY_TO_COUNTRY:
        return CITY_TO_COUNTRY[city]

    global _LOWER_CITY_TO_COUNTRY
    if _LOWER_CITY_TO_COUNTRY is None:
        _LOWER_CITY_TO_COUNTRY = {k.lower(): v for k, v in CITY_TO_COUNTRY.items()}

    normalized = city.strip().lower()
    return _LOWER_CITY_TO_COUNTRY.get(normalized)


def city_to_ioc(city: str) -> Optional[str]:
    """
    Convenience: look up IOC code for a tennis city.

    Combines city_to_country() and country_to_ioc().

    Args:
        city: Name of the city

    Returns:
        3-letter IOC code for the city's country, or None if not found.
    """
    country = city_to_country(city)
    if country:
        return country_to_ioc(country)
    return None
